[package]
name = "keystone"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
include_dir = "0.7.4"
serde = { version = "1.0.228", features = ["derive"] }
surrealdb = "3.0.0"
thiserror = "2.0.18"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
config = "0.15.19"
surrealdb-types = "3.0.0"

[dev-dependencies]
serde_json = "1.0.149"
