[package]
name = "keystone"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
include_dir = "0.7.4"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
surrealdb = "3.0.0"
tempfile = "3.25.0"
thiserror = "2.0.18"
time = { version = "0.3.47", features = ["serde"] }
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.8"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
config = "0.15.19"
surrealdb-types = "3.0.0"
